### ISSUE TITLE
Web Hook Implementation

### ISSUE THREAD

**Issue by DizzyLeChuck** [gocardless/gocardless-dotnet#1]
Fantastic that this is now available! I've been waiting for this since the old .Net one was discontinued.

Is there an interface we can implement when creating a web hook endpoint to make consuming the web hooks easier?

**Comment by jacobpgn** [comment]
Thanks @CheeseNPort, hope you like it!

Unfortunately that's not something we offer in any of our libraries yet, but I've recorded your interest on our side too - it's something we'd love to add at some point. We'll add some suggestions to our [Getting Started](https://developer.gocardless.com/getting-started/) guides in the coming weeks to help you out too.

In the short-term, you could handle the JSON we send however you prefer. You might find it helps to use Newtonsoft.JSON to deserialise the event items into [Event resources](https://github.com/gocardless/gocardless-dotnet/blob/master/GoCardless/Resources/Event.cs)?

**Comment by diwakarniit** [comment]
I am getting the error while opening solution file in VS 2015
Could not load type 'GoCardless.Services.CustomerListResponse' from assembly 'GoCardLess, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by jacobpgn** [comment]
Hi @diwakarniit - you can reach out to [api@gocardless.com](api@gocardless.com) for help getting started with the library.

**Comment by jacobpgn** [comment]
@CheeseNPort An approach to handling (verifying, deserialising, and inspecting) webhooks can now be found in our guides at https://developer.gocardless.com/getting-started/api/staying-up-to-date-with-webhooks/?lang=cs
