### ISSUE TITLE
No support for associating a subscription with a plan?

### ISSUE THREAD

**Issue by Philo** [gocardless/gocardless-dotnet#17]
I was expecting to see an option within `SubscriptionLinks` for adding a Plan reference, should this be a supported feature?

**Comment by timrogers** [comment]
Unfortunately, Plans are a [Dashboard](https://manage.gocardless.com)-only feature. Sorry!

**Comment by Philo** [comment]
Thanks for the response, is this something that will be extended out into the SDK's and API's?
