### ISSUE TITLE
Handling Errors

### ISSUE THREAD

**Issue by trevski** [gocardless/gocardless-dotnet#2]
So i am using the api within functions that are not async in vb.net
I have successfully created the payflow and got back the payflow response and the mandate ref.
I now am trying to post a payment.

 Dim payRequest = New GoCardless.Services.PaymentCreateRequest()
                                payRequest.Amount = orderAmt
                                payRequest.Currency = GoCardless.Services.PaymentCreateRequest.PaymentCurrency.GBP
                                payRequest.Description = Description
                                If bProMode Then
                                    payRequest.Reference = orderPrefix & CStr(oCart.mnCartId)
                                End If
                                payRequest.Links = New GoCardless.Services.PaymentCreateRequest.PaymentLinks() With {
                                         .Mandate = MandateRef
                                    }
                                Dim payResponse As GoCardless.Services.PaymentResponse = oClientApi.Payments.CreateAsync(payRequest).Result

Problem is I am getting a "validation error" so there is something amiss with what I am passing through. However the CreateAsync is throwing the error before I can look at the payResponse object to drill into the error detail.

Should the payResponse object not be returned without throwing the error so you can read the response status and error messages from the payResponse object ?

**Comment by trevski** [comment]
OK I have found my bug in that the OrderAmt should be in an integer of pence rather than a double of pounds and pence. However my comments over the pay response returning regardless of error status I feel should stand.

**Comment by jacobpgn** [comment]
Hi @trevski!

Any error responses from the API will raise an exception (in this case, a `ValidationFailedException`), which you should catch and inspect for full details of the error (including any specific validation errors and the response status.)

You can find more details on the library's errors [here](https://github.com/gocardless/gocardless-dotnet#errors) and the API errors [here](https://developer.gocardless.com/api-reference/#api-usage-errors).

If you need any more support with the library please reach out to the [developer support team](mailto:api@gocardless.com), and if there are any bugs or feature requests for the library then please feel free to open a new issue here!
