### ISSUE TITLE
WebException: The request was aborted: Could not create SSL/TLS secure channel. (.NET Framework 4.5.2, Only SANDBOX)

### ISSUE THREAD

**Issue by SoundarRBT** [gocardless/gocardless-dotnet#29]
**Details:**
The following exception is keep getting thrown from past few days for the projects which were working fine earlier.

**Environment:**
.NET Framework 4.5.2
Gocardless .Net Client 2.18.0
Sandbox

_However the **same environment works for LIVE token. Only SANDBOX doesn't work**._

**Exception:** 
WebException: The request was aborted: Could not create SSL/TLS secure channel.

**Code To Replicate:**
```
using GoCardless;
using System.Threading.Tasks;

namespace GoCardlessTest_.NET4._5._2_GC2._18._0
{
    class Program
    {
	static void Main(string[] args)
	{
	    //WebException: The request was aborted: Could not create SSL/TLS secure channel.
	    TestGocardlessSandboxDotNetFramework452().Wait();

	    //Works
	    TestGocardlessLiveDotNetFramework452().Wait();
	}


	/// <summary>
	/// .NET Framework 4.5.2
	/// Gocardless .Net Client 2.18.0
	/// Sandbox
	/// Status - WebException: The request was aborted: Could not create SSL/TLS secure channel.
	/// </summary>
	/// <returns></returns>
	static async Task TestGocardlessSandboxDotNetFramework452()
	{
	    var client = GoCardlessClient.Create("sandbox_your_token", GoCardlessClient.Environment.SANDBOX);

	    var events = await client.Events.ListAsync();
	}

	/// <summary>
	/// .NET Framework 4.5.2
	/// Gocardless .Net Client 2.18.0
	/// Live
	/// Status - Works
	/// </summary>
	/// <returns></returns>
	static async Task TestGocardlessLiveDotNetFramework452()
	{
	    var client = GoCardlessClient.Create("live_your_token", GoCardlessClient.Environment.LIVE);

	    var events = await client.Events.ListAsync();
	}
    }
}
```

**Comment by lancscoder** [comment]
Hi @SoundarRBT,

Has this ever worked in Sandbox for version 2.18.0?

Also what environment are you running this in? i.e. Windows version etc.

Thanks

**Comment by lancscoder** [comment]
HI @SoundarRBT,

TLS 1.0/1.1 has been disabled in our sandbox environment.

You should have received communications from our support team detailing the end of support of TLS 1.0/1.1.

This can be fixed by upgrading to .net Framework 4.6 or above or depending on your usage/setup you maybe able to set the `SecurityProtocol` - `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

Thanks

**Comment by StuartHadfield** [comment]
Hi @SoundarRBT, I'm going to close this on account of inactivity. If you are still in need of support from the GC team, please feel free to reopen the issue. 😊
