### ISSUE TITLE
JSON deserialisation fails for event details origin of 'customer'

### ISSUE THREAD

**Issue by john-raisingit** [gocardless/gocardless-dotnet#3]
We're currently testing out the sandbox for the new API, so we can move away from the legacy API, and we've been sending test requests from the dashboard to try it out.

We're using version 2.0.3 of the GoCardless Nuget package, and ran into problems with JSON deserialisation for one of the test requests our web hook receives.  The problem seems to be that the JSON contains an `origin` of `customer`, and the `GoCardless.Resources.EventDetailsOrigin` enum doesn't have a value of `customer` on it, so the deserialisation fails.

Here's the JSON of the test request we sent:

```
{
  "events": [
    {
      "id": "EVTESTKR7SRQJ2",
      "created_at": "2017-08-18T11:50:25.476Z",
      "resource_type": "payments",
      "action": "customer_approval_denied",
      "links": {
        "payment": "index_ID_12378"
      },
      "details": {
        "origin": "customer",
        "cause": "customer_approval_denied",
        "description": "The customer denied approval for this payment"
      },
      "metadata": {}
    }
  ]
}
```

The exception details are as follows:

```
{"Error converting value \"customer\" to type 'System.Nullable`1[GoCardless.Resources.EventDetailsOrigin]'. Path 'events[0].details.origin', line 1, position 204."}
```

This result is achieved when trying to deserialise to a list of `GoCardless.Resources.Event`.  Other test requests that have had a different event origin have been successful.

**Comment by jacobpgn** [comment]
Thanks for that @john-raisingit, and apologies for the errors it's caused! We'll try to get a new version out ASAP (hopefully today) and get our documentation updated to include this value too - I'll let you know when that happens.

**Comment by jacobpgn** [comment]
@john-raisingit [v2.0.4](https://www.nuget.org/packages/GoCardless/2.0.4) has been released which fixes this. Have a lovely weekend!

**Comment by john-raisingit** [comment]
Brilliant!  That was fast!  Thanks very much.
