### ISSUE TITLE
Invalid date on List Payments

### ISSUE THREAD

**Issue by paulallington** [gocardless/gocardless-dotnet#4]
The date format produced on the url for listing payments is being rejected by the API:

goCardlessClient.Payments.ListAsync(new PaymentListRequest() { CreatedAt = new PaymentListRequest.CreatedAtParam() { GreaterThan  = dateFrom}});

In the error the Field is "created_date" and detail is "2017-07-23T09:29:12.7580390 01:00 is not a valid date-time."

**Comment by jacobpgn** [comment]
Hey @paulallington, sorry to hear you're having trouble!

What's the value of `dateFrom` in your example?

**Comment by paulallington** [comment]
dateFrom is a DateTime 23/7/2017 09:29:12 (and probably some milliseconds)

**Comment by jacobpgn** [comment]
Thanks - we can reproduce this and will release a patch version shortly and update you here when it's ready!

The timestamp isn't being encoded safely, so the `+` character in the timezone offset is being treated as a space when it's in the query string. As a workaround for the moment, you could apply a small negative time offset as the `-` character is safe, e.g.:

`GreaterThan = new DateTimeOffset(2017, 8, 23, 11, 09, 07, TimeSpan.FromMinutes(-1))`

**Comment by jacobpgn** [comment]
^ Today I learned that GitHub will close an issue if you merge a PR that references it in a different repository!

https://www.nuget.org/packages/GoCardless/2.0.5 should resolve this, but please do let us know if you have any issues. You can also drop an email to api@gocardless.com if you need any help with usage and getting started!

**Comment by paulallington** [comment]
Wonderful, thank you!  I will pull this down and give it a go
