### ISSUE TITLE
InvalidApiUsageException when listing all enabled CustomerBankAccounts

### ISSUE THREAD

**Issue by mikefitz888** [gocardless/gocardless-dotnet#5]
Hi, I'm getting an error message of `No subschema in \"anyOf\" matched.`

Resulting from this call:
`Client.CustomerBankAccounts.All(new CustomerBankAccountListRequest { Customer = id, Enabled = true })`

Some brief testing suggests it's due to the `Enabled` parameter.

As per [https://github.com/gocardless/gocardless-pro-php/issues/24](url)

It may be due to using `True` instead of `true` in the request uri. 

e.g. `https://api-sandbox.gocardless.com/customer_bank_accounts?customer=CU000000000000&enabled=True`

**Comment by georgemabey** [comment]
Hi @mikefitz888,

Thanks for reporting this. 

We'd certainly expect True to work here. 

We're currently working on a fix. We'll make sure to let you know when we have an update!

**Comment by georgemabey** [comment]
Hey again @mikefitz888!

We've just released a patch to fix this specific bug. 

You can find the release notes here - https://github.com/gocardless/gocardless-dotnet/releases/tag/v2.0.6

We hope this helps!
