### ISSUE TITLE
Web App Implementation

### ISSUE THREAD

**Issue by amarjpatel** [gocardless/gocardless-dotnet#6]
- using GoCardless; and  GoCardless.Services; name space in Web app using Sample code given for Console app. what need to be changed to use in Asp.net application.

**Comment by jacobpgn** [comment]
Hey @amarjpatel!

If you want support you can speak to our Developer Support team via api@gocardless.com 

Note that we'll be able to help you with the library and the API, but can't always advise on how best to use other frameworks or tools. That said, the sample code still applies to you - you'll just want to output information to a view instead of writing it to console.

**Comment by amarjpatel** [comment]
Hey Jacob, thanks for prompt reply.based on Developers API , got Console app manage to work. but need to apply it Web Application. I am sure most of the customers must be using web application to get mandate done and redirect back to their web application for simple customer Journey. have already email to api@ but not the good response so far.

**Comment by jacobpgn** [comment]
You should be able to use similar code for your web application - the library is still used in the same way. It might help if you [email the team](api@gocardless.com ) specific questions, with examples of what you are trying and what isn't working, so they can point you in the right direction.

**Comment by amarjpatel** [comment]
let me email them and see what response i get. thanks for the reply.

**Comment by amarjpatel** [comment]
I have raised a support ticket this morning and call support number as well. still, dont have any answer from them yet.

**Comment by jacobpgn** [comment]
Hey @amarjpatel! You've emailed and called lots - this issues channel is for bug reports so we can't provide support here. You will get a response to your email today, but it'll take some time as you're asking for help with using your programming language/framework as opposed to support with our library.

**Comment by amarjpatel** [comment]
Hi there, I tried few different options using session and sending data of redirect id and redirect url to DB. using DB method, it did send once but then I am not getting anymore id or url by debugging page on my local machine, I have sent full code to api@  which i ran it before and got value once in DB but not anymore now.
