### ISSUE TITLE
Suggestion for dates in requests

### ISSUE THREAD

**Issue by DizzyLeChuck** [gocardless/gocardless-dotnet#7]
When making requests for example to create a payment, wouldn't it be better for the format of the parameter for charge date to be "DateTime?" and your SDK to handle formatting it correctly for the Api?

**Comment by jacobpgn** [comment]
Good idea, @CheeseNPort! I think that the way we automatically generate the library might make it a little tricky to make this change soon, but it would make sense to do this so we'll keep it in mind.
